version: '3.4'

services:
  projectorservice:
    image: "repo.labs.greyorange.com/projector-experiments:{{ image_tag }}"
    container_name: "projectorservice"
    network_mode: "host"
    volumes: 
      - type: "bind"
        source: /dev
        target: /dev
      - type: "bind"
        source: /opt/projector_experiment/config/config.json
        target: /projector_release/src/config/config.json
      - type: "bind"
        source: /opt/projector_experiment/log/
        target: /projector_release/src/log/
      - type: "bind"
        source: /etc/localtime
        target: /etc/localtime
    logging:
      driver: "json-file"
      options:
        max-file: '3'
        max-size: '20m'
    privileged: true
    stdin_open: true
    restart: always
    tty: true
    command: bash ./projector_entrypoint_inside_container.sh ${mode:-"app_mode"}
